name: 'RSpec'
description: 'Run RSpecs'

inputs:
  registry:
    description: 'Registry to get image'
    required: false
    default: ghcr.io
  username:
    description: 'Registry login username'
    required: true
  password:
    description: 'Registry login password'
    required: true
  bundle_dockerfile_name:
    description: 'dockerfile name, used in bundle build'
    required: false
    default: Dockerfile
  test_dockerfile_name:
    description: 'dockerfile name, used in test build'
    required: false
    default: Dockerfile
  git_patoken:
    description: 'git personal access token'
    required: false
  platforms:
    description: 'platforms to build'
    required: false
    default: linux/amd64,linux/arm64
  repo_owner:
    description: 'Repo owner to push to'
    required: false
    default: codeboxxtechschool
  push_dir:
    description: 'directory to push to'
    required: true
  branch:
    description: 'branch for tag'
    required: true
  version:
    description: 'version for tag'
    required: true
  bundle_required_files:
    description: 'files that require bundle'
    required: false
  bundle_from:
    description: 'bundle from this image'
    required: true
  yarn_token:
    description: 'Yarn token'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # OR "2"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: "setup repo owner and tag leaf"
      shell: bash
      run: |
        echo "REPO_OWNER=${{ inputs.registry }}/${{ inputs.repo_owner }}" >> $GITHUB_ENV
        echo "TAG_LEAF=${{ inputs.branch }}:${{ inputs.version }}" >> $GITHUB_ENV
    - name: "setup repo path"
      shell: bash
      run: echo "REPO_PATH=${{ env.REPO_OWNER }}/${{ inputs.push_dir }}" >> $GITHUB_ENV
    - name: "setup bundle tag"
      shell: bash
      run: echo "BUNDLE_TAG=${{ env.REPO_PATH }}/bundle/${{ env.TAG_LEAF }}" >> $GITHUB_ENV
    - name: Inspect already bundled manifest
      id: tag_manifest
      shell: bash
      run: |
        if docker manifest inspect ${{ env.BUNDLE_TAG }} >/dev/null; then
          echo ::set-output name=exists::"true"
        else
          echo ::set-output name=exists::"false"
        fi
    - name: Get changed files
      id: changed_files
      if: steps.tag_manifest.outputs.exists == 'true'
      uses: tj-actions/changed-files@v2.0.0
      with:
        files: |
          Gemfile.lock
    - name: Build and push bundle
      if: steps.tag_manifest.outputs.exists == 'false' || steps.changed_files.outputs.any_changed == 'true'
      uses: docker/build-push-action@v2
      with:
        secrets: |
          GIT_PAT=${{ inputs.git_patoken }}
        file: ${{ inputs.bundle_dockerfile_name }}
        platforms: ${{ inputs.platforms }}
        build-args: |
          IMAGE_REF=${{ env.REPO_OWNER }}/${{ inputs.bundle_from }}
        push: true
        tags: |
          ${{ env.BUNDLE_TAG }}
    - name: Build and push for tests
      uses: docker/build-push-action@v2
      with:
        secrets: |
          GIT_PAT=${{ inputs.git_patoken }}
          YARN_TOKEN=${{ inputs.yarn_token }}
        file: ${{ inputs.test_dockerfile_name }}
        platforms: ${{ inputs.platforms }}
        build-args: |
          IMAGE_REF=${{ env.BUNDLE_TAG }}
        push: true
        tags: |
          ${{ env.REPO_PATH }}/${{ env.TAG_LEAF }}
